# Generated by Django 4.2 on 2023-08-24 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_userfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likely',
            new_name='like',
        ),
    ]
