# Generated by Django 4.2 on 2023-09-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
