# Generated by Django 4.2 on 2023-09-01 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
